version: "3.4"

services:
  file:
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}
    command: server --console-address :${MINIO_CONSOLE_PORT} /data
    volumes:
      - file_store:/data
  keycloak: 
    image: jboss/keycloak:12.0.1
    environment:
      DB_VENDOR: ${KEYCLOAK_DB_VENDOR}
      DB_ADDR: ${KEYCLOAK_DB_ADDR}
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/keycloak/realm.json
    ports:
      - ${KEYCLOAK_HTTP_PORT}:8080
      - ${KEYCLOAK_HTTPS_PORT}:8443
    configs:
      - source: realms
        target: /tmp/keycloak/realm.json
    command: -Djava.net.preferIPv4Stack=true -Djboss.bind.address.private=127.0.0.1 -Djboss.bind.address=0.0.0.0

volumes:
  file_store:

configs:
  realms:
    file: ./realm.json