version: '3.4'

services:

  rita_api:
    image: adrianoscazzola/rita-api
    environment:
      PGSQL_DB_HOST: ${PGSQL_DB_HOST}
      PGSQL_DB_PORT: ${PGSQL_DB_PORT}
      RITA_DB_NAME: ${RITA_DB_NAME}
      PGSQL_DB_USER: ${PGSQL_DB_USER}
      PGSQL_DB_PASSWORD: ${PGSQL_DB_PASSWORD}
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
      AUTH_SERVER_SECRET: ${AUTH_SERVER_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_SECURE: ${MINIO_SECURE}
      BUCKET_NAME: robocode
      ROBOCODE_EXAMPLES_PATH: ${RITA_ROBOCODE_EXAMPLES_PATH}
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD}
      SSL_KEY_STORE: ${SSL_KEY_STORE}
      SSL_KEY_STORE_TYPE: ${SSL_KEY_STORE_TYPE}
      SSL_KEY_ALIAS: ${SSL_KEY_ALIAS}
      SSL_KEY_PASSWORD: ${SSL_KEY_PASSWORD}
    ports:
      - ${RITA_API_PORT}:8443
    volumes:
      - ${PWD}/cert/rita.jks:/etc/ssl/certs/rita.jks
  rita_webspa:
    image: adrianoscazzola/rita-webspa
    environment:
      API_URL: ${API_URL}
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
      WEBSOCKETS_BROKER_URL: ${RITA_WEBSOCKETS_BROKER_URL}
    ports:
      - ${RITA_WEBSPA_PORT}:80
