server:
  port: 8081
keycloak:
  realm: RITA
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: robocode-service
  credentials:
    secret: 041b58d4-2a73-4c4b-a8c8-c78304b43191
  use-resource-role-mappings: true
  bearer-only: true
  security-constraints:
    -
     authRoles:
      - robocode-service-admin
     securityCollections:
      - patterns:
        - /api/*
  cors: true
  enabled: true
app:
  robocode:
    homePath: ""