server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/robocode
    username: robocodeuser
    password: robocodepassword
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: update
keycloak:
  realm: RITA
  auth-server-url: http://localhost:8081/auth
  ssl-required: external
  resource: robocode-service
  credentials:
    secret: 041b58d4-2a73-4c4b-a8c8-c78304b43191
  use-resource-role-mappings: true
  bearer-only: true
  security-constraints:
    -
     authRoles:
      - robocode-service-admin
     securityCollections:
      - patterns:
        - /api/*
    - authRoles:
        - robocode-service-user
      securityCollections:
        - patterns:
            - /api/battles/*
    -
      securityCollections:
      - patterns:
        - /api/version
  cors: true
  enabled: true
app:
  robocode:
    homePath: ""