server:
  port: 8081
keycloak:
  realm: RITA
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: robocode-service
  credentials:
    secret: bd8326be-96eb-4cc8-9cd6-c6bf544046db
  use-resource-role-mappings: true
  bearer-only: true
  security-constraints:
    -
     authRoles:
      - robocode-service-admin
     securityCollections:
      - patterns:
        - /api/*
  cors: true
  enabled: true
app:
  robocode:
    homePath: ""