server:
 ssl:
   enabled: ${SSL_ENABLED:false}
   key-store: ${SSL_KEY_STORE}
   key-store-password: ${SSL_KEY_STORE_PASSWORD}
   key-store-type: ${SSL_KEY_STORE_TYPE}
   key-alias: ${SSL_KEY_ALIAS}
   key-password: ${SSL_KEY_PASSWORD}
 port: ${SERVER_PORT:8443}
spring:
  datasource:
    url: jdbc:postgresql://${PGSQL_DB_HOST}:${PGSQL_DB_PORT}/${RITA_DB_NAME}
    username: ${PGSQL_DB_USER}
    password: ${PGSQL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: update
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
keycloak:
  realm: RITA
  auth-server-url: ${AUTH_SERVER_URL}/auth
  ssl-required: external
  resource: robocode-service
  credentials:
    secret: ${AUTH_SERVER_SECRET}
  use-resource-role-mappings: true
  bearer-only: true
  security-constraints:
    -
     authRoles:
      - robocode-service-admin
     securityCollections:
      - patterns:
        - /api/*
    - authRoles:
        - robocode-service-user
      securityCollections:
        - patterns:
            - /api/battles/*
    -
      securityCollections:
      - patterns:
        - /api/version
  cors: true
  enabled: true
app:
  robocode:
    examplesPath: "${ROBOCODE_EXAMPLES_PATH}"
  minio:
    accessKey: ${MINIO_ACCESS_KEY}
    secretKey: ${MINIO_SECRET_KEY}
    host: ${MINIO_HOST}
    port: ${MINIO_PORT}
    secure: ${MINIO_SECURE:false}
    bucketName: ${BUCKET_NAME}
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
