version: '3.4'

services:

  db:
    image: postgres
    volumes:
      - ./pgsql/:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGSQL_DB_PASSWORD}
      - POSTGRES_USER=${PGSQL_DB_USER}
      - POSTGRES_MULTIPLE_DATABASES=${KEYCLOAK_DB_NAME},${RITA_DB_NAME}
volumes:
  db_data: