'use strict';

Blockly.defineBlocksWithJsonArray([{
  'type': 'junior_robot_class',
  'message0': '%{BKY_JUNIOR_ROBOT_CLASS}',
  'args0': [
    {
      'type': 'field_input',
      'name': 'ROBOT_NAME',
      'text': 'MyRobot',
    },
    {
      'type': 'input_dummy',
    },
    {
      'type': 'input_statement',
      'name': 'BODY',
    },
  ],
  'inputsInline': true,
  'colour': 160,
  'tooltip': '%{BKY_JUNIOR_ROBOT_CLASS_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'method_run',
  'message0': '%{BKY_RUN_METHOD}',
  'args0': [
    {
      'type': 'input_dummy',
    },
    {
      'type': 'input_statement',
      'name': 'BODY',
    },
  ],
  'inputsInline': true,
  'previousStatement': null,
  'nextStatement': null,
  'colour': 210,
  'tooltip': '%{BKY_RUN_METHOD_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'method_onHitByBullet',
  'message0': '%{BKY_ON_HIT_BY_BULLET_METHOD}',
  'args0': [
    {
      'type': 'input_dummy',
    },
    {
      'type': 'input_statement',
      'name': 'BODY',
    },
  ],
  'inputsInline': true,
  'previousStatement': null,
  'nextStatement': null,
  'colour': 210,
  'tooltip': '%{BKY_ON_HIT_BY_BULLET_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'method_onHitRobot',
  'message0': '%{BKY_ON_HIT_ROBOT_METHOD}',
  'args0': [
    {
      'type': 'input_dummy',
    },
    {
      'type': 'input_statement',
      'name': 'BODY',
    },
  ],
  'inputsInline': true,
  'previousStatement': null,
  'nextStatement': null,
  'colour': 210,
  'tooltip': '%{BKY_ON_HIT_ROBOT_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'method_onHitWall',
  'message0': '%{BKY_ON_HIT_WALL_METHOD}',
  'args0': [
    {
      'type': 'input_dummy',
    },
    {
      'type': 'input_statement',
      'name': 'BODY',
    },
  ],
  'inputsInline': true,
  'previousStatement': null,
  'nextStatement': null,
  'colour': 210,
  'tooltip': '%{BKY_ON_HIT_WALL_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'method_onScannedRobot',
  'message0': '%{BKY_ON_SCANNED_ROBOT_METHOD}',
  'args0': [
    {
      'type': 'input_dummy',
    },
    {
      'type': 'input_statement',
      'name': 'BODY',
    },
  ],
  'inputsInline': true,
  'previousStatement': null,
  'nextStatement': null,
  'colour': 210,
  'tooltip': '%{BKY_ON_SCANNED_ROBOT_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'move_ahead',
  'message0': '%{BKY_MOVE_AHEAD}',
  'args0': [
    {
      'type': 'field_number',
      'name': 'DISTANCE',
      'value': 1,
      'min': 1,
    },
  ],
  'colour': 220,
  'tooltip': '%{BKY_MOVE_AHEAD_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'move_back',
  'message0': '%{BKY_MOVE_BACK}',
  'args0': [
    {
      'type': 'field_number',
      'name': 'DISTANCE',
      'value': 1,
      'min': 1,
    },
  ],
  'colour': 220,
  'tooltip': '%{BKY_MOVE_BACK_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'move_ahead_left',
  'message0': '%{BKY_MOVE_AHEAD_LEFT}',
  'args0': [
    {
      'type': 'field_number',
      'name': 'DISTANCE',
      'value': 1,
      'min': 1,
    },
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 220,
  'tooltip': '%{BKY_MOVE_AHEAD_LEFT_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'move_ahead_right',
  'message0': '%{BKY_MOVE_AHEAD_RIGHT}',
  'args0': [
    {
      'type': 'field_number',
      'name': 'DISTANCE',
      'value': 1,
      'min': 1,
    },
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 220,
  'tooltip': '%{BKY_MOVE_AHEAD_RIGHT_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'move_back_left',
  'message0': '%{BKY_MOVE_BACK_LEFT}',
  'args0': [
    {
      'type': 'field_number',
      'name': 'DISTANCE',
      'value': 1,
      'min': 1,
    },
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 220,
  'tooltip': '%{BKY_MOVE_BACK_LEFT_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'move_back_right',
  'message0': '%{BKY_MOVE_BACK_RIGHT}',
  'args0': [
    {
      'type': 'field_number',
      'name': 'DISTANCE',
      'value': 1,
      'min': 1,
    },
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 220,
  'tooltip': '%{BKY_MOVE_BACK_RIGHT_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'move_turn_left',
  'message0': '%{BKY_MOVE_TURN_LEFT}',
  'args0': [
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 220,
  'tooltip': '%{BKY_MOVE_TURN_LEFT_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'move_turn_right',
  'message0': '%{BKY_MOVE_TURN_RIGHT}',
  'args0': [
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 220,
  'tooltip': '%{BKY_MOVE_TURN_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'move_turn',
  'message0': '%{BKY_MOVE_TURN}',
  'args0': [
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 220,
  'tooltip': '%{BKY_MOVE_TURN_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'action_turn_gun_left',
  'message0': '%{BKY_TURN_GUN_LEFT}',
  'args0': [
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 230,
  'tooltip': '%{BKY_TURN_GUN_LEFT_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'action_turn_gun_right',
  'message0': '%{BKY_TURN_GUN_RIGHT}',
  'args0': [
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 230,
  'tooltip': '%{BKY_TURN_GUN_RIGHT_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'action_turn_gun_to',
  'message0': '%{BKY_TURN_GUN_TO}',
  'args0': [
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 230,
  'tooltip': '%{BKY_TURN_GUN_TO_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'action_bear_gun_to',
  'message0': '%{BKY_BEAR_GUN_TO}',
  'args0': [
    {
      'type': 'field_angle',
      'name': 'DEGRESS',
      'angle': 90,
    },
  ],
  'colour': 230,
  'tooltip': '%{BKY_BEAR_GUN_TO_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'action_do_nothing',
  'message0': '%{BKY_DO_NOTHING}',
  'colour': 230,
  'tooltip': '%{BKY_DO_NOTHING_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'action_do_nothing_turns',
  'message0': '%{BKY_DO_NOTHING_TURNS}',
  'args0': [
    {
      'type': 'field_number',
      'name': 'TURNS',
      'value': 1,
      'min': 1,
    },
  ],
  'colour': 230,
  'tooltip': '%{BKY_DO_NOTHING_TURNS_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'action_fire',
  'message0': '%{BKY_FIRE}',
  'colour': 230,
  'tooltip': '%{BKY_FIRE_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'action_fire_power',
  'message0': '%{BKY_FIRE_POWER}',
  'args0': [
    {
      'type': 'field_number',
      'name': 'POWER',
      'value': 0.1,
      'min': 0.1,
      'max': 3,
      'precision': 0.0001,
    },
  ],
  'colour': 230,
  'tooltip': '%{BKY_FIRE_POWER_TOOLTIP}',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'variable_energy',
  'message0': '%{BKY_VARIABLE_ENERGY}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_ENERGY_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'field_height',
  'message0': '%{BKY_FIELD_HEIGHT}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_FIELD_HEIGHT_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'field_width',
  'message0': '%{BKY_FIELD_WIDTH}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_FIELD_WIDTH_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_gun_bearing',
  'message0': '%{BKY_VARIABLE_GUN_BEARING}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_GUN_BEARING_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_gun_heading',
  'message0': '%{BKY_VARIABLE_GUN_HEADING}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_GUN_HEADING_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_gun_ready',
  'message0': '%{BKY_VARIABLE_GUN_READY}',
  'output': 'Boolean',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_GUN_READY_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_heading',
  'message0': '%{BKY_VARIABLE_HEADING}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_HEADING_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_hit_by_bullet_angle',
  'message0': '%{BKY_VARIABLE_HIT_BY_BULLET_ANGLE}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_HIT_BY_BULLET_ANGLE_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_hit_by_bullet_bearing',
  'message0': '%{BKY_VARIABLE_HIT_BY_BULLET_BEARING}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_HIT_BY_BULLET_BEARING_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_hit_robot_angle',
  'message0': '%{BKY_VARIABLE_HIT_ROBOT_ANGLE}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_HIT_ROBOT_ANGLE_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_hit_robot_bearing',
  'message0': '%{BKY_VARIABLE_HIT_ROBOT_BEARING}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_HIT_ROBOT_BEARING_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_hit_wall_angle',
  'message0': '%{BKY_VARIABLE_HIT_WALL_ANGLE}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_HIT_WALL_ANGLE_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_hit_wall_bearing',
  'message0': '%{BKY_VARIABLE_HIT_WALL_BEARING}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_HIT_WALL_BEARING_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_others',
  'message0': '%{BKY_VARIABLE_OTHERS}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_OTHERS_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_robot_x',
  'message0': '%{BKY_VARIABLE_ROBOT_X}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_ROBOT_X_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_robot_y',
  'message0': '%{BKY_VARIABLE_ROBOT_Y}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLE_ROBOT_Y_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_scanned_angle',
  'message0': '%{BKY_VARIABLE_SCANNED_ANGLE}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLEE_SCANNED_ANGLE_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_scanned_bearing',
  'message0': '%{BKY_VARIABLE_SCANNED_BEARING}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLEE_SCANNED_BEARING_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_scanned_distance',
  'message0': '%{BKY_VARIABLE_SCANNED_DISTANCE}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLEE_SCANNED_DISTANCE_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_scanned_energy',
  'message0': '%{BKY_VARIABLE_SCANNED_ENERGY}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLEE_SCANNED_ENERGY_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_scanned_heading',
  'message0': '%{BKY_VARIABLE_SCANNED_HEADING}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLEE_SCANNED_HEADING_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'variable_scanned_velocity',
  'message0': '%{BKY_VARIABLE_SCANNED_VELOCITY}',
  'output': 'Number',
  'colour': 240,
  'tooltip': '%{BKY_VARIABLEE_SCANNED_VELOCITY_TOOLTIP}',
  'helpUrl': '',
},
{
  'type': 'set_some_colours',
  'message0': '%{BKY_SET_SOME_COLOURS}',
  'args0': [
    {
      'type': 'field_colour',
      'name': 'BODY',
      'colour': '#ff0000',
    },
    {
      'type': 'field_colour',
      'name': 'GUN',
      'colour': '#ffffff',
    },
    {
      'type': 'field_colour',
      'name': 'RADAR',
      'colour': '#6633ff',
    },
  ],
  'colour': 250,
  'tooltip': '',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
{
  'type': 'set_all_colours',
  'message0': '%{BKY_SET_ALL_COLOURS}',
  'args0': [
    {
      'type': 'field_colour',
      'name': 'BODY',
      'colour': '#ff0000',
    },
    {
      'type': 'field_colour',
      'name': 'GUN',
      'colour': '#ffffff',
    },
    {
      'type': 'field_colour',
      'name': 'RADAR',
      'colour': '#6633ff',
    },
    {
      'type': 'field_colour',
      'name': 'BULLET',
      'colour': '#ffff66',
    },
    {
      'type': 'field_colour',
      'name': 'SCANARC',
      'colour': '#33cc00',
    },
  ],
  'colour': 250,
  'tooltip': '',
  'helpUrl': '',
  'previousStatement': null,
  'nextStatement': null,
},
]);
